# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0cuser_service\"!\n\x0cGetRpRequest\x12\x11\n\tcapy_uuid\x18\x01 \x01(\t\"}\n\rGetRpResponse\x12\x0b\n\x03\x63rp\x18\x01 \x01(\x05\x12\r\n\x05\x63oins\x18\x02 \x01(\x05\x12\x0b\n\x03prp\x18\x03 \x01(\x05\x12\r\n\x05level\x18\x04 \x01(\x05\x12\x12\n\nfirst_name\x18\x05 \x01(\t\x12\x11\n\tlast_name\x18\x06 \x01(\t\x12\r\n\x05login\x18\x07 \x01(\t2R\n\x0bUserService\x12\x43\n\x06get_rp\x12\x1a.user_service.GetRpRequest\x1a\x1b.user_service.GetRpResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETRPREQUEST']._serialized_start=36
  _globals['_GETRPREQUEST']._serialized_end=69
  _globals['_GETRPRESPONSE']._serialized_start=71
  _globals['_GETRPRESPONSE']._serialized_end=196
  _globals['_USERSERVICE']._serialized_start=198
  _globals['_USERSERVICE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
